composerdata:
  image: harshjv/composer-data:0.9.16-1.0

mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=assistance

phpnginx:
  image: harshjv/php-nginx:0.9.16-1.0
  volumes_from:
    - composerdata
  links:
    - mysql
  ports:
    - "8090:80"
  volumes:
    - ./nginx:/etc/nginx/sites-available
    - ./:/var/www
